name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        repository: JnCrMx/helpy-library-common
        ref: refs/heads/master
        token: ${{ secrets.GitHub_PAT }}
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build and install helpy-library-common
      run: mvn install --file ../helpy-library-common/pom.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml
